# Use Ubuntu as base image
FROM ubuntu:22.04

# Avoid prompts from apt
ENV DEBIAN_FRONTEND=noninteractive

# Install Apache, MariaDB, PHP, and other dependencies
RUN apt-get update && \
    apt-get install -y \
    apache2 \
    mariadb-server \
    php \
    php-mysql \
    libapache2-mod-php \
    curl \
    vim \
    mc \
    htop \
    net-tools \
    openjdk-21-jdk \
    iputils-ping \
    curl \
    wget \
    iproute2 \
    dnsutils \
    telnet \
    netcat \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*



# Enable Apache modules
RUN a2enmod rewrite php8.1

# Copy test web application
COPY webserver/index.php /var/www/html/
COPY webserver/db-test.php /var/www/html/
COPY webserver/init-db.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/init-db.sh

# Copy startup script
COPY webserver/start.sh /usr/local/bin/start.sh
RUN chmod +x /usr/local/bin/start.sh

# Expose Apache port
EXPOSE 80

# Start services
CMD ["/usr/local/bin/start.sh"]
